#!/usr/bin/env node
/**
 * @fileoverview Shell Build Script for Live Character Guide v6
 * @module src/scripts/build-shell
 * @version 3.0.0
 *
 * @description
 * Stage 2 of the v6 build pipeline. Copies shell + generated parts + data → dist/
 *
 * Changes from v5.12 (v2.0.1):
 * - Parts copied from build/parts-l{N}/ (generated by build-layers.mjs)
 *   instead of src/parts-l{N}/ (manual v5.12 parts)
 * - Data copied from root data/ instead of src/data/
 * - Added footer generation and layer name validation
 * - Added layer-config.json validation per §0.17
 *
 * Usage:
 *   node src/scripts/build-shell.mjs
 */

import { createHash } from 'crypto';
import { readFile, writeFile, readdir, mkdir, copyFile, rm, stat } from 'fs/promises';
import { existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const SRC_DIR = join(ROOT, 'src');
const SHELL_DIR = join(SRC_DIR, 'shell');
const BUILD_DIR = join(ROOT, 'build');
const DATA_DIR = join(ROOT, 'data');
const DIST_DIR = join(ROOT, 'dist');
const ASSETS_SRC = join(SRC_DIR, 'assets');
const ASSETS_DIST = join(DIST_DIR, 'assets');
const VERSION_PATH = join(SRC_DIR, 'VERSION');

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

async function ensureDir(dir) {
  if (!existsSync(dir)) {
    await mkdir(dir, { recursive: true });
  }
}

async function copyDir(src, dest) {
  await ensureDir(dest);
  const entries = await readdir(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);

    if (entry.isDirectory()) {
      await copyDir(srcPath, destPath);
    } else {
      await copyFile(srcPath, destPath);
    }
  }
}

function log(level, message) {
  const timestamp = new Date().toISOString();
  const prefix = level === 'ERROR' ? '❌' : level === 'WARN' ? '⚠️' : '✓';
  console.log(`[${timestamp}] ${prefix} ${message}`);
}

// ============================================================================
// LAYER CONFIG VALIDATION (§0.17)
// ============================================================================

async function validateLayerConfig() {
  const configPath = join(BUILD_DIR, 'layer-config.json');
  if (!existsSync(configPath)) {
    log('WARN', 'build/layer-config.json not found, skipping layer name validation');
    return null;
  }

  const config = JSON.parse(await readFile(configPath, 'utf-8'));
  log('INFO', `Layer config loaded: v${config.version}`);

  // Validate layer names
  const expectedLabels = ['Минимальный', 'Глубокий', 'Экспертный'];
  const expectedNames = ['Basic', 'Deep', 'Expert'];
  const expectedColors = ['#22c55e', '#38bdf8', '#8b5cf6'];

  for (let i = 0; i < config.layers.length; i++) {
    const layer = config.layers[i];
    if (layer.label !== expectedLabels[i]) {
      log('ERROR', `Layer ${layer.id} label mismatch: expected "${expectedLabels[i]}", got "${layer.label}"`);
    }
    if (layer.name !== expectedNames[i]) {
      log('ERROR', `Layer ${layer.id} name mismatch: expected "${expectedNames[i]}", got "${layer.name}"`);
    }
    if (layer.color !== expectedColors[i]) {
      log('WARN', `Layer ${layer.id} color mismatch: expected "${expectedColors[i]}", got "${layer.color}"`);
    }
  }

  return config;
}

// ============================================================================
// BUILD SHELL
// ============================================================================

async function buildShell() {
  log('INFO', 'Starting shell build...');

  // Validate layer config first
  const layerConfig = await validateLayerConfig();

  // Read version
  let version = 'unknown';
  if (existsSync(VERSION_PATH)) {
    version = (await readFile(VERSION_PATH, 'utf-8')).trim();
    log('INFO', `Version: ${version}`);
  }

  // Verify build-layers.mjs has been run
  if (!existsSync(join(BUILD_DIR, 'parts-l1', 'manifest.json'))) {
    log('ERROR', 'build-layers.mjs has not been run yet! Run it first:');
    log('ERROR', '  node scripts/build-layers.mjs');
    process.exit(1);
  }

  // Clean dist directory
  if (existsSync(DIST_DIR)) {
    await rm(DIST_DIR, { recursive: true });
  }
  await ensureDir(DIST_DIR);
  await ensureDir(ASSETS_DIST);

  // 1. Copy shell index.html
  const shellIndex = join(SHELL_DIR, 'index.html');
  let buildHash;
  if (existsSync(shellIndex)) {
    let indexContent = await readFile(shellIndex, 'utf-8');

    // Replace version placeholder
    indexContent = indexContent.replace(/5\.12\.0/g, version);

    // Calculate hash for cache busting (before adding hash to content)
    buildHash = createHash('sha256')
      .update(indexContent)
      .digest('hex')
      .slice(0, 8);

    // Add build metadata
    indexContent = indexContent.replace(
      '<!-- Live Character Guide - Shell v5.12.0 -->',
      `<!-- Live Character Guide - Shell v${version} -->\n<!-- Build: ${buildHash} -->\n<!-- Generated: ${new Date().toISOString()} -->`
    );

    await writeFile(join(DIST_DIR, 'index.html'), indexContent);
    log('INFO', 'Copied shell/index.html → dist/index.html');
  } else {
    log('ERROR', 'shell/index.html not found');
    process.exit(1);
  }

  // 2. Copy shell styles.css
  const shellStyles = join(SHELL_DIR, 'styles.css');
  if (existsSync(shellStyles)) {
    await copyFile(shellStyles, join(ASSETS_DIST, 'shell-styles.css'));
    log('INFO', 'Copied shell/styles.css → dist/assets/shell-styles.css');
  } else {
    log('ERROR', 'shell/styles.css not found');
    process.exit(1);
  }

  // 3. Copy lazy-loader.js
  const lazyLoader = join(SHELL_DIR, 'lazy-loader.js');
  if (existsSync(lazyLoader)) {
    let loaderContent = await readFile(lazyLoader, 'utf-8');

    // Replace version
    loaderContent = loaderContent.replace(/5\.12\.0/g, version);

    await writeFile(join(ASSETS_DIST, 'lazy-loader.js'), loaderContent);
    log('INFO', 'Copied shell/lazy-loader.js → dist/assets/lazy-loader.js');
  } else {
    log('ERROR', 'shell/lazy-loader.js not found');
    process.exit(1);
  }

  // 3b. Copy shell/widgets/ → dist/widgets/ (all widgets including widget-utils.js)
  // E1: Auto-sync prevents DC18-style divergence between src/shell/widgets/ and root widgets/
  const widgetsSrc = join(SHELL_DIR, 'widgets');
  const widgetsDist = join(DIST_DIR, 'widgets');
  if (existsSync(widgetsSrc)) {
    await copyDir(widgetsSrc, widgetsDist);
    const widgetFiles = await readdir(widgetsDist);
    log('INFO', `Copied shell/widgets/ → dist/widgets/ (${widgetFiles.length} files: ${widgetFiles.join(', ')})`);
  } else {
    log('WARN', 'shell/widgets/ not found, skipping');
  }

  // 3c. Copy event-bus.js to dist root (required by index.html)
  const eventBusSrc = join(SHELL_DIR, 'event-bus.js');
  if (existsSync(eventBusSrc)) {
    await copyFile(eventBusSrc, join(DIST_DIR, 'event-bus.js'));
    log('INFO', 'Copied shell/event-bus.js → dist/event-bus.js');
  } else {
    log('ERROR', 'shell/event-bus.js not found');
    process.exit(1);
  }

  // 4. Copy generated parts from build/parts-l{N}/ (instead of src/parts-l{N}/)
  const layers = ['1', '2', '3'];
  for (const layer of layers) {
    const buildPartsDir = join(BUILD_DIR, `parts-l${layer}`);
    const destDir = join(DIST_DIR, `parts-l${layer}`);

    if (existsSync(buildPartsDir)) {
      await copyDir(buildPartsDir, destDir);
      const files = await readdir(destDir);
      log('INFO', `Copied build/parts-l${layer}/ → dist/parts-l${layer}/ (${files.length} files)`);
    } else {
      log('WARN', `build/parts-l${layer}/ not found, skipping`);
    }
  }

  // 5. Copy assets (favicon, preview-card, etc.)
  if (existsSync(ASSETS_SRC)) {
    const assetFiles = await readdir(ASSETS_SRC);
    for (const file of assetFiles) {
      const srcPath = join(ASSETS_SRC, file);
      const destPath = join(ASSETS_DIST, file);
      const s = await stat(srcPath);

      if (s.isFile()) {
        await copyFile(srcPath, destPath);
      }
    }
    log('INFO', `Copied ${assetFiles.length} assets → dist/assets/`);
  }

  // 5b. Copy data files from root data/ (instead of src/data/)
  const DATA_DIST = join(DIST_DIR, 'data');
  if (existsSync(DATA_DIR)) {
    await copyDir(DATA_DIR, DATA_DIST);
    const dataFiles = await readdir(DATA_DIST);
    log('INFO', `Copied data/ → dist/data/ (${dataFiles.length} files)`);
  } else {
    log('WARN', 'data/ directory not found, skipping');
  }

  // 6. Create build hash file (use the same hash as in HTML)
  await writeFile(join(DIST_DIR, 'build.hash'), buildHash);

  // 7. Copy 404.html from src/404.html (fixed path per BUG-74)
  const notFound = join(SRC_DIR, '404.html');
  if (existsSync(notFound)) {
    await copyFile(notFound, join(DIST_DIR, '404.html'));
    log('INFO', 'Copied src/404.html → dist/404.html');
  } else {
    log('WARN', 'src/404.html not found, skipping');
  }

  // 8. Copy sitemap.xml and robots.txt for SEO
  const sitemap = join(ROOT, 'sitemap.xml');
  const robots = join(ROOT, 'robots.txt');
  if (existsSync(sitemap)) {
    await copyFile(sitemap, join(DIST_DIR, 'sitemap.xml'));
    log('INFO', 'Copied sitemap.xml → dist/sitemap.xml');
  }
  if (existsSync(robots)) {
    await copyFile(robots, join(DIST_DIR, 'robots.txt'));
    log('INFO', 'Copied robots.txt → dist/robots.txt');
  }

  // 9. Create root index.html for backward compatibility (GitHub Pages fallback)
  await copyFile(join(DIST_DIR, 'index.html'), join(ROOT, 'index.html'));
  log('INFO', 'Copied dist/index.html → index.html (root fallback)');

  // 10. Create root build.hash for CI compatibility
  await copyFile(join(DIST_DIR, 'build.hash'), join(ROOT, 'build.hash'));
  log('INFO', 'Copied dist/build.hash → build.hash (root fallback)');

  // 11. Create root assets/ for backward compatibility
  const rootAssets = join(ROOT, 'assets');
  if (existsSync(rootAssets)) {
    await rm(rootAssets, { recursive: true });
  }
  await copyDir(ASSETS_DIST, rootAssets);
  log('INFO', 'Copied dist/assets/ → assets/ (root fallback)');

  // 12. Copy event-bus.js to root for backward compatibility
  if (existsSync(join(DIST_DIR, 'event-bus.js'))) {
    await copyFile(join(DIST_DIR, 'event-bus.js'), join(ROOT, 'event-bus.js'));
    log('INFO', 'Copied dist/event-bus.js → event-bus.js (root fallback)');
  }

  // 13. Copy widgets/ to root for backward compatibility (index.html references widgets/*.js)
  const rootWidgets = join(ROOT, 'widgets');
  if (existsSync(rootWidgets)) {
    await rm(rootWidgets, { recursive: true });
  }
  if (existsSync(widgetsDist)) {
    await copyDir(widgetsDist, rootWidgets);
    const widgetRootFiles = await readdir(rootWidgets);
    log('INFO', `Copied dist/widgets/ → widgets/ (root fallback, ${widgetRootFiles.length} files)`);
  }

  // 14. Copy data/ to root for backward compatibility (lazy-loader fetches data/*.json)
  const rootData = join(ROOT, 'data');
  if (existsSync(rootData)) {
    await rm(rootData, { recursive: true });
  }
  if (existsSync(DATA_DIST)) {
    await copyDir(DATA_DIST, rootData);
    const dataRootFiles = await readdir(rootData);
    log('INFO', `Copied dist/data/ → data/ (root fallback, ${dataRootFiles.length} files)`);
  }

  // 15. Copy parts-l{N}/ to root for backward compatibility (lazy-loader fetches parts-l{N}/*.html)
  for (const layer of layers) {
    const rootPartsDir = join(ROOT, `parts-l${layer}`);
    if (existsSync(rootPartsDir)) {
      await rm(rootPartsDir, { recursive: true });
    }
    const distPartsDir = join(DIST_DIR, `parts-l${layer}`);
    if (existsSync(distPartsDir)) {
      await copyDir(distPartsDir, rootPartsDir);
      const partRootFiles = await readdir(rootPartsDir);
      log('INFO', `Copied dist/parts-l${layer}/ → parts-l${layer}/ (root fallback, ${partRootFiles.length} files)`);
    }
  }

  log('INFO', `Shell build complete! Hash: ${buildHash}`);

  return { hash: buildHash, version };
}

// ============================================================================
// ENTRY POINT
// ============================================================================

buildShell()
  .then(result => {
    console.log('\n============================================');
    console.log('SHELL BUILD SUCCESSFUL');
    console.log('============================================');
    console.log(`Version: ${result.version}`);
    console.log(`Hash: ${result.hash}`);
    console.log(`Output: ${DIST_DIR}`);
    process.exit(0);
  })
  .catch(err => {
    log('ERROR', `Build failed: ${err.message}`);
    console.error(err);
    process.exit(1);
  });
