#!/bin/bash
# Cleanup script for removing legacy files after migration to shell architecture
# Run this after merging the fixes

set -e

echo "=== Cleaning up legacy files ==="

# Remove legacy zero-install file (no longer generated)
if [ -f "live-char-guide-zero-install.html" ]; then
    echo "Removing legacy: live-char-guide-zero-install.html"
    rm -f live-char-guide-zero-install.html
fi

# Remove legacy build hash files in root (now only in dist/)
if [ -f "build-zero-install.hash" ]; then
    echo "Removing legacy: build-zero-install.hash"
    rm -f build-zero-install.hash
fi

# Remove old src/parts if it exists (now using src/parts-l{1,2,3})
if [ -d "src/parts" ]; then
    echo "Removing legacy: src/parts/"
    rm -rf src/parts/
fi

# Remove old src/manifest directory if structure.json was the only file
if [ -f "src/manifest/structure.json" ]; then
    echo "Updating: src/manifest/structure.json (new format)"
fi

# Clean dist directory (will be regenerated)
if [ -d "dist" ]; then
    echo "Cleaning: dist/"
    rm -rf dist/
fi

# Clean root fallback files (will be regenerated by build)
if [ -f "index.html" ]; then
    echo "Removing root fallback (will regenerate): index.html"
    rm -f index.html
fi

if [ -f "build.hash" ]; then
    echo "Removing root fallback (will regenerate): build.hash"
    rm -f build.hash
fi

if [ -d "assets" ]; then
    echo "Removing root fallback (will regenerate): assets/"
    rm -rf assets/
fi

echo ""
echo "=== Cleanup complete ==="
echo "Run 'pnpm run build:all' to regenerate artifacts"
